// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Retorna los últimos `limit` eventos de auditoría desde la base de datos
/// en `db_path`, ordenados del más reciente al más antiguo.
///
/// ## Argumentos
/// - `db_path`: ruta al archivo SQLite de Drasus.
/// - `limit`: cuántos eventos devolver (el Panel solicita 50 normalmente).
///
/// ## Estrategia de carga
/// `AuditLogRepository::load_chain()` carga todos los eventos ordenados ASC
/// (del más antiguo al más reciente). Se toma el tail con `.rev().take(limit)`
/// y se invierte de vuelta para que el más reciente aparezca primero en el
/// Panel. Esto es eficiente para el volumen de EPIC-0 (decenas a miles de
/// eventos); en EPIC-1+ con millones de eventos se sustituirá por una query
/// paginada directa.
///
/// ## Por qué async (sin #[frb(sync)])
/// Igual que `get_jobs_summary`: hace I/O a SQLite y no debe bloquear el
/// hilo principal de Flutter.
///
/// ## Error handling en la frontera
/// Si la conexión falla o la cadena está vacía, retorna un `Vec` vacío.
/// El Panel muestra "sin eventos" — estado válido en una BD recién creada.
Future<List<AuditEventSummary>> getRecentAuditEvents(
        {required String dbPath, required BigInt limit}) =>
    RustLib.instance.api
        .crateApiAuditGetRecentAuditEvents(dbPath: dbPath, limit: limit);

/// Resumen de un evento de auditoría para el Panel Operativo.
///
/// Solo se incluyen los campos necesarios para la visualización:
/// acción, entidad, cuándo ocurrió y el hash de cadena que permite
/// verificación visual rápida.
///
/// ## Tipos en Rust vs Dart
///
/// | Campo               | Rust     | Dart     | Nullable en Dart |
/// |---------------------|----------|----------|-----------------|
/// | `id`                | `String` | `String` | No              |
/// | `action_type`       | `String` | `String` | No              |
/// | `entity_type`       | `String` | `String` | No              |
/// | `created_at`        | `i64`    | `int`    | No              |
/// | `audit_chain_hash`  | `String` | `String` | No              |
///
/// ## Sobre `audit_chain_hash`
/// En el tipo interno [`shared::public_interface::AuditEvent`], `audit_chain_hash`
/// es `Option<String>` — el evento génesis (el primero de la cadena) no tiene
/// predecesor, por lo que su campo es `None`. Al cruzar la frontera FFI se
/// convierte a `String` con `unwrap_or_default()`: el evento génesis muestra
/// una cadena vacía en el Panel, lo cual es correcto (no hay hash anterior
/// que mostrar).
class AuditEventSummary {
  /// Identificador único del evento (UUID v4 como cadena de texto).
  final String id;

  /// Tipo de acción registrada (ej. "ORDER_STATE_CHANGE", "USER_VETO",
  /// "CLOCK_NTP_SYNC"). Siempre presente; nunca vacío.
  final String actionType;

  /// Tipo de entidad sobre la que ocurrió la acción (ej. "ORDER",
  /// "JOB", "CLOCK"). Siempre presente; nunca vacío.
  final String entityType;

  /// Momento de creación del evento en nanosegundos desde el Unix epoch.
  final PlatformInt64 createdAt;

  /// Hash SHA-256 encadenado. Es el hash de este evento, que a su vez
  /// incluye el hash del evento anterior en su cálculo — cualquier
  /// modificación retroactiva de un evento rompe todos los hashes
  /// posteriores. El Panel muestra los últimos 8 caracteres para
  /// verificación visual rápida.
  ///
  /// El evento génesis (primero de la cadena) muestra cadena vacía aquí
  /// porque todavía no tiene predecesor que encadenar.
  final String auditChainHash;

  const AuditEventSummary({
    required this.id,
    required this.actionType,
    required this.entityType,
    required this.createdAt,
    required this.auditChainHash,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      actionType.hashCode ^
      entityType.hashCode ^
      createdAt.hashCode ^
      auditChainHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditEventSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          actionType == other.actionType &&
          entityType == other.entityType &&
          createdAt == other.createdAt &&
          auditChainHash == other.auditChainHash;
}
