// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Retorna el timestamp actual del reloj de producción de Drasus en
/// nanosegundos desde el Unix epoch (1970-01-01 00:00:00 UTC).
///
/// **Tipo de retorno:** `i64`. El reloj interno usa `i64` porque SQLite
/// almacena los timestamps como enteros con signo, y se mantiene el mismo
/// tipo en toda la pila para evitar conversiones con pérdida.
///
/// **Garantía de ownership:** `i64` es un primitivo de tamaño fijo copiado
/// por valor al cruzar la frontera — no hay heap involucrado, no hay memoria
/// que liberar en ninguno de los dos lados.
///
/// **`#[frb(sync)]`:** indica a flutter_rust_bridge que esta función es
/// síncrona — Dart la llama y recibe el valor en el mismo frame, sin
/// necesidad de `await`. Solo se usa para operaciones que no hacen I/O
/// (no van a disco ni a red) y retornan en microsegundos.
PlatformInt64 getClockTimestampNs() =>
    RustLib.instance.api.crateApiClockGetClockTimestampNs();
