// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_error`

/// Ejecuta una descarga híbrida soberana (Bulk + Delta REST) y devuelve el
/// resultado completo cuando la descarga termina.
///
/// ## Parámetros
/// - `db_path`: ruta al archivo SQLite de Drasus (ej. `/home/usuario/drasus.db`).
/// - `data_dir`: directorio donde se guardarán los archivos descargados.
///   Se crea automáticamente con `create_dir_all` si no existe.
/// - `symbol`: símbolo del mercado en mayúsculas (ej. `"BTCUSDT"`).
/// - `broker_url`: URL base del servidor Bulk (ej. `"https://data.binance.vision"`).
/// - `start_ns`, `end_ns`: límites del rango en nanosegundos desde epoch.
///   Conversión desde Dart: `dateTime.microsecondsSinceEpoch * 1000`.
/// - `timeframe`: intervalo temporal (ej. `"1m"`, `"5m"`, `"1h"`, `"1d"`).
/// - `output_type`: tipo de salida (`"ticks"` o `"bars"`). Informativo en EPIC-1;
///   el transformer aguas abajo lo usará en una Story posterior.
///
/// ## Ownership al cruzar la frontera FFI
/// `DownloadJobResult` se serializa en un objeto Dart. Rust libera la memoria;
/// Dart recibe su propia copia. No hay memoria compartida entre los dos lados.
///
/// ## Por qué async (Opción A)
/// La descarga puede durar segundos o minutos. Si fuera síncrona (`#[frb(sync)]`)
/// bloquearía el hilo principal de Flutter causando janks. flutter_rust_bridge
/// la convierte en `Future<DownloadJobResult>` en Dart: el Flutter Engineer usa
/// `await submitDownloadJob(...)` con un spinner de `transitionIndigo` mientras dura.
///
/// ## Error handling
/// Si algo falla (BD inaccesible, error de red, disco lleno) se retorna un
/// `DownloadJobResult` con `error` no nulo y campos numéricos en 0.
/// El Flutter Engineer muestra `GlowBanner(type: error, message: result.error!)`
/// en la Zona B (ADR-0117 Techo Fijo: sin manejo elaborado de errores en EPIC-1).
Future<DownloadJobResult> submitDownloadJob(
        {required String dbPath,
        required String dataDir,
        required String symbol,
        required String brokerUrl,
        required PlatformInt64 startNs,
        required PlatformInt64 endNs,
        required String timeframe,
        required String outputType}) =>
    RustLib.instance.api.crateApiDataFetcherSubmitDownloadJob(
        dbPath: dbPath,
        dataDir: dataDir,
        symbol: symbol,
        brokerUrl: brokerUrl,
        startNs: startNs,
        endNs: endNs,
        timeframe: timeframe,
        outputType: outputType);

/// Consulta el estado actual de un Job de descarga desde la tabla `jobs`.
///
/// ## Parámetros
/// - `db_path`: ruta al archivo SQLite de Drasus.
/// - `job_id`: UUID del Job devuelto en `DownloadJobResult.job_id`.
///
/// ## Cuándo llamarlo (EPIC-1)
/// El Flutter Engineer llama a esta función UNA VEZ después de que el
/// Future de `submitDownloadJob` resuelva, para poblar la Zona B con el
/// estado final y el progreso. En EPIC-1 no hay polling periódico —
/// ese patrón requiere el submit asíncrono en segundo plano (gap documentado).
///
/// ## Ownership al cruzar la frontera FFI
/// `Option<JobStatusDto>` se serializa como `JobStatusDto?` en Dart.
/// Rust libera la memoria; Dart recibe su copia. Sin memoria compartida.
///
/// ## Error handling
/// Devuelve `null` en Dart si el `job_id` no existe en la BD o si la
/// conexión falla. El Flutter Engineer comprueba el null antes de renderizar.
Future<JobStatusDto?> getJobStatus(
        {required String dbPath, required String jobId}) =>
    RustLib.instance.api
        .crateApiDataFetcherGetJobStatus(dbPath: dbPath, jobId: jobId);

/// Lista todos los registros de `sovereign_download_records`, del más reciente
/// al más antiguo. Sin paginación — adecuado para el volumen de EPIC-1.
///
/// ## Parámetros
/// - `db_path`: ruta al archivo SQLite de Drasus.
///
/// ## Ownership al cruzar la frontera FFI
/// `Vec<DownloadRecordDto>` se serializa en una `List<DownloadRecordDto>` Dart.
/// Rust libera el vector; Dart recibe copias de los datos. Sin memoria compartida.
///
/// ## Error handling
/// Devuelve lista vacía si la BD no existe o la query falla. La Zona C
/// mostrará `GlowEmpty({message: 'Sin descargas aún.'})` — correcto en
/// BD recién creada o sin descargas previas.
///
/// ## Nota para el Flutter Engineer
/// Esta función solo expone `id`, `created_at` y `source_endpoint`.
/// La tabla `sovereign_download_records` no almacena `symbol`, `bytes_total`
/// ni `status` (ver migración 0006 — esos campos no existen). El símbolo y los
/// bytes del último job vienen del `DownloadJobResult` de `submitDownloadJob`;
/// guardarlos en `_lastResult` en el estado del widget para la Zona B.
Future<List<DownloadRecordDto>> listDownloadRecords({required String dbPath}) =>
    RustLib.instance.api.crateApiDataFetcherListDownloadRecords(dbPath: dbPath);

/// Resultado de una descarga completada o fallida.
///
/// Propietario de memoria: Rust crea esta estructura; flutter_rust_bridge la
/// serializa y la libera. Dart recibe una copia en su propio heap — sin memoria
/// compartida entre los dos lados.
///
/// | Campo                   | Rust            | Dart     | Nullable en Dart |
/// |-------------------------|-----------------|----------|-----------------|
/// | `job_id`                | `String`        | `String` | No               |
/// | `record_id`             | `String`        | `String` | No               |
/// | `bulk_files_downloaded` | `u64`           | `int`    | No               |
/// | `delta_bytes`           | `u64`           | `int`    | No               |
/// | `total_bytes`           | `u64`           | `int`    | No               |
/// | `error`                 | `Option<String>`| `String?`| Sí               |
class DownloadJobResult {
  /// UUID del Job persistido en la tabla `jobs`. Cadena vacía si falló
  /// antes de crear el Job (ej. error de conexión a la BD).
  /// Propietario: Rust genera el UUID; Dart lo recibe de solo lectura.
  final String jobId;

  /// UUID del registro persistido en `sovereign_download_records`.
  /// Cadena vacía si la descarga falló antes de persistir el registro.
  final String recordId;

  /// Archivos Bulk descargados exitosamente. Vale 0 si la descarga falló.
  final BigInt bulkFilesDownloaded;

  /// Bytes del tramo Delta REST descargado. Vale 0 si no hubo Delta o falló.
  final BigInt deltaBytes;

  /// Total de bytes descargados (Bulk + Delta). Vale 0 si falló.
  final BigInt totalBytes;

  /// Descripción del error si la descarga falló; `null` en Dart si fue
  /// exitosa. El Flutter Engineer muestra este mensaje en un `GlowBanner`
  /// de tipo error en la Zona B.
  final String? error;

  const DownloadJobResult({
    required this.jobId,
    required this.recordId,
    required this.bulkFilesDownloaded,
    required this.deltaBytes,
    required this.totalBytes,
    this.error,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      recordId.hashCode ^
      bulkFilesDownloaded.hashCode ^
      deltaBytes.hashCode ^
      totalBytes.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadJobResult &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          recordId == other.recordId &&
          bulkFilesDownloaded == other.bulkFilesDownloaded &&
          deltaBytes == other.deltaBytes &&
          totalBytes == other.totalBytes &&
          error == other.error;
}

/// Registro de una descarga persistido en `sovereign_download_records`.
///
/// Solo expone los campos disponibles en la tabla (ver migración 0006).
/// Los campos `symbol`, `bytes_total` y `status` no existen en esta tabla —
/// vienen del `DownloadJobResult` devuelto por `submitDownloadJob`.
///
/// | Campo             | Rust     | Dart     | Nullable en Dart |
/// |-------------------|----------|----------|-----------------|
/// | `id`              | `String` | `String` | No               |
/// | `created_at`      | `i64`    | `int`    | No               |
/// | `source_endpoint` | `String` | `String` | No               |
class DownloadRecordDto {
  /// UUID único del registro de descarga.
  final String id;

  /// Timestamp de creación en nanosegundos desde epoch.
  /// Conversión a Dart: `DateTime.fromMicrosecondsSinceEpoch(createdAt ~/ 1000)`.
  final PlatformInt64 createdAt;

  /// URL/endpoint exacto de la fuente (Bulk S3 o REST) que sirvió los datos.
  /// Truncar a 40 caracteres en la `GlowTable` con `GlowTooltip` al hover.
  final String sourceEndpoint;

  const DownloadRecordDto({
    required this.id,
    required this.createdAt,
    required this.sourceEndpoint,
  });

  @override
  int get hashCode =>
      id.hashCode ^ createdAt.hashCode ^ sourceEndpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadRecordDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          sourceEndpoint == other.sourceEndpoint;
}

/// Estado de un Job de descarga soberana leído desde la tabla `jobs`.
///
/// Útil para que el Flutter Engineer muestre el estado final en la Zona B
/// después de que el Future de `submitDownloadJob` resuelva. En EPIC-1 no
/// se usa para polling periódico (ver §Decisión de diseño arriba).
///
/// | Campo        | Rust  | Dart | Nullable en Dart |
/// |--------------|-------|------|-----------------|
/// | `id`         | `String` | `String` | No         |
/// | `state`      | `String` | `String` | No         |
/// | `progress`   | `u8`     | `int`    | No         |
/// | `created_at` | `i64`    | `int`    | No         |
/// | `updated_at` | `i64`    | `int`    | No         |
class JobStatusDto {
  /// UUID del Job (mismo valor que `DownloadJobResult.job_id`).
  final String id;

  /// Estado del Job como cadena. Valores posibles:
  /// "QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELLED".
  /// El Flutter Engineer mapea estos valores a los chips de color del
  /// §Estados Semánticos de la Cáscara Visual.
  final String state;

  /// Porcentaje de avance (0–100). El backend fija 100 al completar.
  /// En EPIC-1 este campo siempre llega a 100 al resolver el Future —
  /// no hay actualizaciones intermedias (sin polling).
  final int progress;

  /// Timestamp de creación del Job en nanosegundos desde epoch.
  final PlatformInt64 createdAt;

  /// Timestamp de la última actualización del Job en nanosegundos desde epoch.
  final PlatformInt64 updatedAt;

  const JobStatusDto({
    required this.id,
    required this.state,
    required this.progress,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      state.hashCode ^
      progress.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JobStatusDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          state == other.state &&
          progress == other.progress &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
