// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Retorna los últimos 20 trabajos (en cualquier estado) desde la base de
/// datos en `db_path`, ordenados del más reciente al más antiguo.
///
/// ## Argumentos
/// - `db_path`: ruta al archivo SQLite de Drasus (ej. `/home/user/drasus.db`).
///   Se convierte internamente a la URL de conexión que SQLx entiende.
///
/// ## Ownership al cruzar la frontera FFI
/// `Vec<JobSummary>` se serializa por flutter_rust_bridge en una lista Dart.
/// Rust libera el vector; Dart recibe una copia de los datos en su propio
/// heap. No hay memoria compartida — cada lado gestiona la suya.
///
/// ## Por qué async (sin #[frb(sync)])
/// Esta función hace I/O (abre la base de datos, ejecuta una query SQLite).
/// Si fuera síncrona bloquearía el hilo principal de Flutter durante el acceso
/// al disco, causando frames caídos. flutter_rust_bridge la convierte en un
/// `Future<List<JobSummary>>` en Dart: Flutter llama `await getJobsSummary()`
/// y el motor de UI sigue dibujando mientras espera.
///
/// ## Error handling en la frontera
/// Si la conexión a la BD falla o la query falla, se retorna un `Vec` vacío.
/// El Panel muestra "sin datos" en vez de colapsar — adecuado para un Panel
/// de diagnóstico donde un error de BD es observable en sí mismo.
Future<List<JobSummary>> getJobsSummary({required String dbPath}) =>
    RustLib.instance.api.crateApiJobsGetJobsSummary(dbPath: dbPath);

/// Resumen de un trabajo, con solo los campos necesarios para el Panel
/// Operativo. Todos los campos son primitivos o `String` — tipos que
/// flutter_rust_bridge puede transportar a través de la frontera FFI sin
/// serialización adicional.
///
/// ## Tipos en Rust vs Dart
///
/// | Campo      | Rust     | Dart     | Nullable en Dart |
/// |------------|----------|----------|-----------------|
/// | `id`       | `String` | `String` | No              |
/// | `job_type` | `String` | `String` | No              |
/// | `state`    | `String` | `String` | No              |
/// | `created_at` | `i64`  | `int`    | No              |
///
/// `created_at` es un timestamp en nanosegundos desde el Unix epoch (i64).
/// Dart lo representa como `int` (entero de 64 bits con signo), compatible.
class JobSummary {
  /// Identificador único del trabajo (UUID v4 como cadena de texto).
  /// Propietario: Rust genera el UUID; Dart lo recibe de solo lectura.
  final String id;

  /// Tipo de trabajo registrado al momento del envío (ej. "BACKTEST").
  final String jobType;

  /// Estado actual del trabajo: "QUEUED", "RUNNING", "COMPLETED", "FAILED"
  /// o "CANCELLED". Se almacena y transmite como String para no acoplar
  /// el Panel al enum interno de Rust.
  final String state;

  /// Momento de creación del trabajo en nanosegundos desde el Unix epoch.
  /// Se usa i64 porque SQLite almacena el campo como INTEGER con signo,
  /// y se mantiene el mismo tipo en toda la pila para evitar truncamientos.
  final PlatformInt64 createdAt;

  const JobSummary({
    required this.id,
    required this.jobType,
    required this.state,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ jobType.hashCode ^ state.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JobSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          jobType == other.jobType &&
          state == other.state &&
          createdAt == other.createdAt;
}
