// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../frb_generated.dart';

part 'verification.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `dispatch`, `invalid`

/// Despacha la verificación de `feature_id` con `input_json` hacia el
/// backend real y devuelve un resultado estructurado.
///
/// ## Contrato (FIJO -- el Flutter-Engineer construye la UI del Banco de
/// Pruebas contra esta firma exacta)
/// 1. Si `input_json` no es JSON válido, o no coincide con la estructura
///    que `feature_id` espera, o `feature_id` no está en el catálogo de
///    [`list_verifiable_features`]: devuelve `input_status = Invalid` SIN
///    ejecutar el backend.
/// 2. Si el input es válido: ejecuta la `verify_*` real de la feature
///    (round-trip completo -- BD efímera propia, migraciones, feature
///    ejercitada de punta a punta) y devuelve `ok` + `output_json` con la
///    respuesta completa del backend serializada, o `error` con el motivo
///    si el backend rechazó la operación.
///
/// ## Ownership al cruzar la frontera FFI
/// `VerificationOutcome` se serializa por flutter_rust_bridge en un objeto
/// Dart. Rust libera la memoria; Dart recibe su propia copia -- sin memoria
/// compartida entre los dos lados.
///
/// ## Error handling
/// Nunca hace panic ante input malformado o `feature_id` desconocido -- eso
/// se captura como `input_status = Invalid`. Los fallos del backend (BD
/// inaccesible, validación de dominio rechazada, etc.) ya vienen
/// capturados dentro de cada `Output.error` (contrato ADR-0142); `dispatch`
/// solo los promueve al nivel superior de `VerificationOutcome.error`.
Future<VerificationOutcome> verifyFeature(
        {required String featureId, required String inputJson}) =>
    RustLib.instance.api.crateApiVerificationVerifyFeature(
        featureId: featureId, inputJson: inputJson);

/// Devuelve el catálogo completo de features verificables, en el mismo
/// orden en que aparecen los brazos de [`verify_feature`]. La UI del Banco
/// de Pruebas usa este catálogo para poblar el selector y el input por
/// defecto -- añadir una feature nueva solo exige un elemento más aquí y un
/// brazo más en `verify_feature`, sin tocar ningún otro binding FFI.
///
/// ## Ownership al cruzar la frontera FFI
/// `Vec<FeatureDescriptor>` se serializa en una `List<FeatureDescriptor>`
/// Dart. Rust libera el vector; Dart recibe copias de los datos. Sin
/// memoria compartida.
List<FeatureDescriptor> listVerifiableFeatures() =>
    RustLib.instance.api.crateApiVerificationListVerifiableFeatures();

/// Un elemento del catálogo de features verificables -- usado por la UI del
/// Banco de Pruebas para poblar el selector y precargar un input de ejemplo.
///
/// | Campo | Rust | Dart | Nullable en Dart |
/// |---|---|---|---|
/// | `id` | `String` | `String` | No |
/// | `display_name` | `String` | `String` | No |
/// | `example_input_json` | `String` | `String` | No |
class FeatureDescriptor {
  /// Identificador en kebab-case: el mismo que espera [`verify_feature`]
  /// y el subcomando `drasus verify <feature_id>` del CLI (ADR-0142).
  final String id;

  /// Nombre legible para el selector de la UI (nunca el `id` crudo).
  final String displayName;

  /// JSON de ejemplo que deserializa correctamente contra el `Input`
  /// tipado de la feature -- listo para precargar el campo de texto del
  /// Banco de Pruebas. Reutiliza los ejemplos ya documentados en
  /// `crates/app/src/main.rs` (subcomando `verify`) -- una sola fuente de
  /// verdad para "cómo se ve un input válido de humo".
  final String exampleInputJson;

  const FeatureDescriptor({
    required this.id,
    required this.displayName,
    required this.exampleInputJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^ displayName.hashCode ^ exampleInputJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeatureDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          exampleInputJson == other.exampleInputJson;
}

@freezed
sealed class InputStatus with _$InputStatus {
  const InputStatus._();

  /// El `input_json` es sintácticamente válido y su estructura coincide
  /// exactamente con lo que la feature `feature_id` espera.
  const factory InputStatus.valid() = InputStatus_Valid;

  /// El `input_json` no es JSON válido, o es JSON válido que no coincide
  /// con la estructura esperada (campo obligatorio ausente, tipo
  /// incorrecto), o `feature_id` no está en el catálogo. `reason` es el
  /// mensaje de `serde_json` (incluye línea/columna cuando aplica) o,
  /// para `feature_id` desconocido, la indicación de consultar el
  /// catálogo vigente.
  const factory InputStatus.invalid({
    required String reason,
  }) = InputStatus_Invalid;
}

/// Resultado estructurado de una verificación despachada de forma genérica
/// por [`verify_feature`]. Es la ÚNICA forma de respuesta del Banco de
/// Pruebas -- el mismo shape para las 15 features, sin importar cuál se
/// invoque.
///
/// | Campo | Rust | Dart | Nullable en Dart |
/// |---|---|---|---|
/// | `input_status` | `InputStatus` | `InputStatus` | No |
/// | `ok` | `bool` | `bool` | No |
/// | `output_json` | `String` | `String` | No |
/// | `error` | `Option<String>` | `String?` | Sí |
///
/// Propietario de memoria: Rust crea esta estructura; flutter_rust_bridge la
/// serializa y la libera. Dart recibe su propia copia -- sin memoria
/// compartida entre los dos lados.
class VerificationOutcome {
  /// Si el input fue rechazado ANTES de llamar al backend, esta variante
  /// trae el motivo. Cuando es `Invalid`, `ok` siempre es `false`,
  /// `output_json` siempre es `""` y `error` siempre es `None` -- el
  /// problema ya quedó descrito aquí, no hace falta duplicarlo.
  final InputStatus inputStatus;

  /// Copia de `output.ok` del backend cuando `input_status == Valid`.
  /// Cuando `input_status == Invalid`, vale `false` (nunca se llegó a
  /// ejecutar el backend).
  final bool ok;

  /// El `Output` completo del backend, serializado con
  /// `serde_json::to_string`. Cadena vacía si `input_status == Invalid`.
  /// El propietario puede inspeccionar cualquier campo del backend real
  /// (no solo `ok`/`error`) sin que el Bridge declare un DTO nuevo por
  /// cada una de las 15 features.
  final String outputJson;

  /// Mensaje de error de negocio cuando `ok == false` y
  /// `input_status == Valid` (el backend corrió pero rechazó la
  /// operación). Viene del campo `error` que TODO `*VerifyOutput` expone
  /// (contrato ADR-0142). `None` si `ok == true` o si
  /// `input_status == Invalid`.
  final String? error;

  const VerificationOutcome({
    required this.inputStatus,
    required this.ok,
    required this.outputJson,
    this.error,
  });

  @override
  int get hashCode =>
      inputStatus.hashCode ^ ok.hashCode ^ outputJson.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerificationOutcome &&
          runtimeType == other.runtimeType &&
          inputStatus == other.inputStatus &&
          ok == other.ok &&
          outputJson == other.outputJson &&
          error == other.error;
}
